services:
  app:
    build: .  # Usa o Dockerfile
    image: php:8.3-apache-bullseye
    container_name: laravel-app
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
      - COMPOSER_ALLOW_SUPERUSER=1
    depends_on:
      - mysql
  # Banco de Dados MySQL
  mysql:
    image: mysql:8.0
    container_name: laravel-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: